#!/usr/bin/env bash

#set -xeuo pipefail

HOST=g2
IP=192.168.10.21

CURDIR=$(pwd)

HOSTDIR=${CURDIR}/${HOST}

mkdir ${HOSTDIR}

echo "1: Generating CA Key"
openssl genrsa -aes256 -out ${HOSTDIR}/${HOST}-ca-key.pem 4096
echo "===================================================="

echo "2: Generating CA Certificate"
openssl req -new -x509 -days 365 -key ${HOSTDIR}/${HOST}-ca-key.pem -sha256 -out ${HOSTDIR}/${HOST}-ca.pem
echo "===================================================="

echo "3: Generating Server Key"
openssl genrsa -out ${HOSTDIR}/${HOST}-server-key.pem 4096
echo "===================================================="

echo "4: Generating Server CSR"
openssl req -subj "/CN=$HOST" -sha256 -new -key ${HOSTDIR}/${HOST}-server-key.pem -out ${HOSTDIR}/${HOST}-server.csr
echo "===================================================="

echo "5: Configuring Server CSR"
echo subjectAltName = DNS:${HOST},IP:${IP},IP:127.0.0.1 >> ${HOSTDIR}/${HOST}-extfile.cnf
echo extendedKeyUsage = serverAuth >> ${HOSTDIR}/${HOST}-extfile.cnf
echo "===================================================="

echo "6: Generate Signed Certificate"
openssl x509 -req -days 365 -sha256 -in ${HOSTDIR}/${HOST}-server.csr -CA ${HOSTDIR}/${HOST}-ca.pem -CAkey ${HOSTDIR}/${HOST}-ca-key.pem -CAcreateserial -out ${HOSTDIR}/${HOST}-server-cert.pem -extfile ${HOSTDIR}/${HOST}-extfile.cnf
echo "===================================================="

echo "7: Generate Client Key"
openssl genrsa -out ${HOSTDIR}/${HOST}-client-key.pem 4096
echo "===================================================="

echo "8: Generate Client CSR"
openssl req -subj '/CN=client' -new -key ${HOSTDIR}/${HOST}-client-key.pem -out ${HOSTDIR}/${HOST}-client.csr
echo "===================================================="

echo "9: Configuring Client"
echo extendedKeyUsage = clientAuth > ${HOSTDIR}/${HOST}-client-extfile.cnf
echo "===================================================="

echo "10: Generate Client Signed Certificate"
openssl x509 -req -days 365 -sha256 -in ${HOSTDIR}/${HOST}-client.csr -CA ${HOSTDIR}/${HOST}-ca.pem -CAkey ${HOSTDIR}/${HOST}-ca-key.pem -CAcreateserial -out ${HOSTDIR}/${HOST}-client-cert.pem -extfile ${HOSTDIR}/${HOST}-client-extfile.cnf
echo "===================================================="
